// lib/modules/profile/controller/profile_controller.dart

import 'package:flutter/material.dart';
import '../../../model/employee_model.dart';

class ProfileController extends ChangeNotifier {
  bool _isLoading = false;
  EmployeeModel? _employee;

  bool get isLoading => _isLoading;
  EmployeeModel? get employee => _employee;

  static final List<Map<String, dynamic>> rawEmployees = [

    {
      'empNo': '446',
      'name': 'Raja Talathoti',
      'status': 'Active',
      'group': 'Executive',
      'subgroup': 'E6',
      'subgroupText': 'DGM',
      'position': 'Deputy General Manager-System',
      'seniority': '00000001',
      'payscale': '90000-240000',
      'dept': 'System',
      'subarea': 'Head Office Nag',
      'gender': 'Male',
      'deptName': 'System',
      'dob': '26-04-1976',
      'qual': 'D.C.M.E., \'A\' LEVEL, \'B\' LEVEL(MCA)',
      'basic': '1,01,760.00',
      'apptDate': '12-11-2007',
      'dosl': '01-07-2024',
      'dopp': '08-05-2017',
      'datePsc': 'N/A',
      'actDoj': '08-08-2024',
      'latPromo': '01-07-2024',
      'confDue': 'N/A',
      'internalRec': 'N/A',
      'regularization': 'N/A',
      'retireDate': '30-04-2036',
      'caste': 'SC',
      'marital': 'Married',
      'mobile': '9860801149',
      'email': 'RAJA@MOIL.NIC.IN',
      'voter': '1234567890',
      'uan': '100292843101',
      'pension': '10248',
      'passport': '02331',
      'pan': 'ADIPT5111G',
      'gratuity': '3788888851',
      'fb': '00000446',
      'dl': 'MH40 20120016077',
      'aadhar': '557092546386',
      'blood': 'A+',
      'praan': '110153877952',
      'ppo': 'N/A',
      'newMed': 'N/A',
      'oldMed': 'N/A',
      'penalty': 'N/A',
      'epf': 'SSPF',
      'pfNo': 'T1382',
      'pensionPf': 'MP/JBP/133E/10027',
      'purchasePrice': 'Rs. 15,72,808.07',
      'fileNo': '559',
      'bankKey': 'SBIN0063868',
      'bankAcc': '20517130864',
      'nomGratuity': 'MRS. ANITHA TALATHOTI',
      'nomGratuityRel': 'WIFE',
      'nomPf': 'MRS. ANITHA TALATHOTI',
      'nomPfRel': 'WIFE',
      'nomPension': 'MRS. ANITHA TALATHOTI',
      'nomPensionRel': 'WIFE',
      'permAddress': 'Epuru (vill-po) Ananthavaram (via), Tenali(Tq) Guntur 522301',
      'tempAddress': 'Orange city park kamptee road yerkheda kamptee 441002',
      'emergAddress': 'Epuru(Vil-Po), Ananathavaram(Via),Tenali(Tq) Guntur(Dt) 522301',
      'spouse': 'Anitha Talathoti',
      'spouseDob': '06-08-1988',
      'child1': 'Pavitra Talathoti',
      'childDob1': '12-01-2009',
      'child2': 'Vikranth Talathoti',
      'childDob2': '26-12-2013',
      'child3': 'N/A',
      'childDob3': '',
      'mother': 'Chiranjeevi Talathoti',
      'motherDob': '16-01-1960',
      'father': 'Srinivasa Rao Talathoti',
      'fatherDob': '04-05-1953',
      'other': 'N/A',
      'otherDob': '',
      'sepDate': 'N/A',
      'sepReason': 'N/A',
      'hireReason': 'New Position',
      'spouseAcc': 'N/A',
      'empRoll': 'RO',
      'nominees': [],
      'serviceHistory': [],
      'reportingOfficer': '16194',
      'reportingOfficer1': '0',
    },
    {
      'empNo': '540',
      'name': 'Swapnil Kanthiram Manpe',
      'status': 'Active',
      'group': 'Executive',
      'subgroup': 'E4',
      'subgroupText': 'Chief Manager',
      'position': 'Chief Manager (System)',
      'seniority': '00000007',
      'payscale': '70000-200000',
      'dept': 'System',
      'subarea': 'Head Office Nag',
      'gender': 'Male',
      'deptName': 'System',
      'dob': '12-09-1986',
      'qual': 'B.E.[IT]',
      'basic': '70,000.00',
      'apptDate': '02-12-2011',
      'dosl': '01-07-2025',
      'dopp': '16-08-2025',
      'datePsc': 'N/A',
      'actDoj': '16-08-2025',
      'latPromo': 'N/A',
      'confDue': 'N/A',
      'internalRec': 'N/A',
      'regularization': 'N/A',
      'retireDate': '30-09-2046',
      'caste': 'SC',
      'marital': 'Married',
      'mobile': '9960485712',
      'email': 'SWAPNILMANPE@MOIL.NIC.IN',
      'voter': '1234567890',
      'uan': '100377068471',
      'pension': '11993',
      'passport': '02606',
      'pan': 'BLTPM3281J',
      'gratuity': 'N/A',
      'fb': 'N/A',
      'dl': 'MH4020110011046',
      'aadhar': '441250612453',
      'blood': 'O+',
      'praan': '110119993569',
      'ppo': 'N/A',
      'newMed': 'N/A',
      'oldMed': 'N/A',
      'penalty': 'N/A',
      'epf': 'MOMP',
      'pfNo': 'MP/JBP/133/13821',
      'pensionPf': 'MP/JBP/133/13821',
      'purchasePrice': 'Rs. 8,70,181.18',
      'fileNo': 'N/A',
      'bankKey': 'SBIN0004710',
      'bankAcc': '30533778301',
      'nomGratuity': 'MRS SHWETA MANPE',
      'nomGratuityRel': 'WIFE',
      'nomPf': 'MRS SHWETA MANPE',
      'nomPfRel': 'WIFE',
      'nomPension': 'MRS SHWETA MANPE',
      'nomPensionRel': 'WIFE',
      'permAddress': 'Flat No. 09, Kale Layout, Behind Si Kirana Store Arya Nagar, Koradi Road, Nagpur Nagpur 440013',
      'tempAddress': 'Flat No. 09, Kale Layout, Behind Si Kirana Store Arya Nagar, Koradi Road, Nagpur Nagpur 440013',
      'emergAddress': 'MOIL Bhawan Chhaoni, Katol Road, Nagpur Nagpur 440013',
      'spouse': 'Shweta Manpe',
      'spouseDob': '22-11-1990',
      'child1': 'Prashil Manpe',
      'childDob1': '10-07-2021',
      'child2': 'N/A',
      'childDob2': '',
      'child3': 'N/A',
      'childDob3': '',
      'mother': 'Karuna Manpe',
      'motherDob': '01-01-1959',
      'father': 'Kanthiram Manpe',
      'fatherDob': '01-07-1957',
      'other': 'N/A',
      'otherDob': '',
      'sepDate': 'N/A',
      'sepReason': 'N/A',
      'hireReason': 'New Position',
      'spouseAcc': 'N/A',
      'empRoll': 'RO1',
      'nominees': [],
      'serviceHistory': [],
      'reportingOfficer': '446',
      'reportingOfficer1': '16194',
    },
    {
      'empNo': '16194',
      'name': 'Rakesh Tumane',
      'status': 'Active',
      'group': 'Executive',
      'subgroup': 'DR',
      'subgroupText': 'Directors',
      'position': 'Director-Finance',
      'seniority': '00000001',
      'payscale': '180000-340000',
      'dept': 'Director (Fin.)',
      'subarea': 'Head Office Nag',
      'gender': 'Male',
      'deptName': 'Head Office Finance',
      'dob': '20-08-1970',
      'qual': 'MBA, FCMA,CIMA,AICPA, MBA (Fin), BE (Comp. Science), Diploma in French',
      'basic': '2,54,480.00',
      'apptDate': '28-09-2017',
      'dosl': '28-09-2017',
      'dopp': '28-09-2017',
      'datePsc': 'N/A',
      'actDoj': '27-09-2018',
      'latPromo': 'N/A',
      'confDue': 'N/A',
      'internalRec': 'N/A',
      'regularization': 'N/A',
      'retireDate': '31-08-2030',
      'caste': 'OT',
      'marital': 'Married',
      'mobile': '9869003314',
      'email': 'DIRFIN@MOIL.NIC.IN',
      'voter': 'N/A',
      'uan': '100300400215',
      'pension': 'N/A',
      'passport': 'N/A',
      'pan': 'ACEPT4553B',
      'gratuity': 'Rs. 3532552.35',
      'fb': 'N/A',
      'dl': 'N/A',
      'aadhar': '913083116260',
      'blood': 'O+',
      'praan': '110018121610',
      'ppo': 'N/A',
      'newMed': 'N/A',
      'oldMed': 'N/A',
      'penalty': 'N/A',
      'epf': 'SSPF',
      'pfNo': 'T1445',
      'pensionPf': 'NG/NAG/3664E/25070',
      'purchasePrice': 'Rs. 3532552.35',
      'fileNo': 'N/A',
      'bankKey': 'HDFC0000012',
      'bankAcc': '50100097412132',
      'nomGratuity': 'MRS. LEENA TUMANE',
      'nomGratuityRel': 'WIFE',
      'nomPf': 'MRS. LEENA TUMANE',
      'nomPfRel': 'WIFE',
      'nomPension': 'MRS. LEENA TUMANE',
      'nomPensionRel': 'WIFE',
      'permAddress': 'RH-20, Vyankatesh Nagar, Nandanvan  NAGPUR 440018',
      'tempAddress': 'Director Bunglow No.03, MOIL West Court, Katol Road  Nagpur 440013',
      'emergAddress': 'N/A',
      'spouse': 'Leena Tumane',
      'spouseDob': '18-06-1977',
      'child1': 'Rekha Shreshtha Tumane',
      'childDob1': '16-10-2001',
      'child2': 'N/A',
      'childDob2': '',
      'child3': 'Shiv Tumane',
      'childDob3': '28-01-2010',
      'mother': 'Rekha Tumane',
      'motherDob': '07-07-1950',
      'father': 'Madhusudan Tumane',
      'fatherDob': '13-11-1945',
      'other': 'N/A',
      'otherDob': '',
      'sepDate': 'N/A',
      'sepReason': 'N/A',
      'hireReason': 'New Position',
      'spouseAcc': 'N/A',
      'empRoll': 'RO1',
      'nominees': [],
      'serviceHistory': [],
      'reportingOfficer': '17110',
      'reportingOfficer1': '0',
    },
    {
      'empNo': '4410',
      'name': 'Ranjeet Singh Chouhan',
      'status': 'Active',
      'group': 'Executive',
      'subgroup': 'E5',
      'subgroupText': 'Asst. Gen. Manager',
      'position': 'Assistant General Manager-System',
      'seniority': '00000004',
      'payscale': '80000-220000',
      'dept': 'System',
      'subarea': 'Head Office Nag',
      'gender': 'Male',
      'deptName': 'System',
      'dob': '09-09-1976',
      'qual': 'BSC,DCA,PGDCA,HONOUR\'S DIP,MCA, MBA[PROJ.MGT.]',
      'basic': '83,610.00',
      'apptDate': '28-12-1998',
      'dosl': '01-07-2025',
      'dopp': '16-08-2025',
      'datePsc': 'N/A',
      'actDoj': '16-08-2025',
      'latPromo': 'N/A',
      'confDue': 'N/A',
      'internalRec': 'N/A',
      'regularization': 'N/A',
      'retireDate': '30-09-2036',
      'caste': 'OT',
      'marital': 'Married',
      'mobile': '8530122221',
      'email': 'RANJEETSINGH@MOIL.NIC.IN',
      'voter': 'N/A',
      'uan': '100307959152',
      'pension': '413',
      'passport': '02336',
      'pan': 'ADPPC8349G',
      'gratuity': 'Rs. 12,85,954.60',
      'fb': 'N/A',
      'dl': 'N/A',
      'aadhar': '981325763039',
      'blood': 'B+',
      'praan': '110177887694',
      'ppo': 'N/A',
      'newMed': 'N/A',
      'oldMed': 'N/A',
      'penalty': 'N/A',
      'epf': 'MOMH',
      'pfNo': 'NG/NAG/3600/3714',
      'pensionPf': 'NG/NAG/3600/3714',
      'purchasePrice': 'Rs. 12,85,954.60',
      'fileNo': 'N/A',
      'bankKey': 'SBIN0005999',
      'bankAcc': '11205035270',
      'nomGratuity': 'MRS.NEETU SINGH',
      'nomGratuityRel': 'WIFE',
      'nomPf': 'MRS.NEETU SINGH',
      'nomPfRel': 'WIFE',
      'nomPension': 'MRS.NEETU SINGH',
      'nomPensionRel': 'WIFE',
      'permAddress': '47, Welcome Society, Near Fire Engg. College, Katol Road Nagpur 440013',
      'tempAddress': '47, Welcome Society, Near Fire Engg. College, Katol Road Nagpur 440013',
      'emergAddress': 'Moil Bhawan Katol Road Nagpur 440013',
      'spouse': 'Nitu Chouhan',
      'spouseDob': '03-02-1978',
      'child1': 'Nandini Chouhan',
      'childDob1': '10-16-2005',
      'child2': 'Yuvraj Chouhan',
      'childDob2': '28-06-2007',
      'child3': 'N/A',
      'childDob3': '',
      'mother': 'Ramadevi Chouhan',
      'motherDob': '06-09-1940',
      'father': 'Vijay Chouhan',
      'fatherDob': '05-09-1935',
      'other': 'N/A',
      'otherDob': '',
      'sepDate': 'N/A',
      'sepReason': 'N/A',
      'hireReason': 'New Position',
      'spouseAcc': 'N/A',
      'empRoll': 'RO',
      'nominees': [],
      'serviceHistory': [],
      'reportingOfficer': '446',
      'reportingOfficer1': '16194',
    },
    {
      'empNo': '4428',
      'name': 'B.C.N. Gautam',
      'status': 'Active',
      'group': 'Executive',
      'subgroup': 'E5',
      'subgroupText': 'Asst. Gen. Manager',
      'position': 'Assistant General Manager-System',
      'seniority': '00000002',
      'payscale': '80000-220000',
      'dept': 'System',
      'subarea': 'Head Office Nag',
      'gender': 'Male',
      'deptName': 'System',
      'dob': '02-09-1968',
      'qual': 'B.Sc., M. Sc. (Computer Sience)',
      'basic': '88,710.00',
      'apptDate': '19-03-1998',
      'dosl': '01-07-2022',
      'dopp': '01-04-2014',
      'datePsc': 'N/A',
      'actDoj': '15-10-2022',
      'latPromo': 'N/A',
      'confDue': 'N/A',
      'internalRec': 'N/A',
      'regularization': 'N/A',
      'retireDate': '30-09-2028',
      'caste': 'OT',
      'marital': 'Married',
      'mobile': '7744061070',
      'email': 'BCNGAUTAM@MOIL.NIC.IN',
      'voter': 'N/A',
      'uan': '100016081977',
      'pension': '1269',
      'passport': '02260',
      'pan': 'AIMPG8474A',
      'gratuity': 'Rs. 14,00,787.61',
      'fb': 'N/A',
      'dl': 'N/A',
      'aadhar': '370578947981',
      'blood': 'B+',
      'praan': '110173216453',
      'ppo': 'N/A',
      'newMed': 'N/A',
      'oldMed': 'N/A',
      'penalty': 'N/A',
      'epf': 'MOMH',
      'pfNo': 'NG/NAG/3600/4755',
      'pensionPf': 'NG/NAG/3600/4755',
      'purchasePrice': 'Rs. 14,00,787.61',
      'fileNo': 'N/A',
      'bankKey': 'SBIN0063868',
      'bankAcc': '20529486466',
      'nomGratuity': 'MRS. BHUMESHWARI B.GAUTAM',
      'nomGratuityRel': 'WIFE',
      'nomPf': 'MRS. BHUMESHWARI B.GAUTAM',
      'nomPfRel': 'WIFE',
      'nomPension': 'MRS. BHUMESHWARI B.GAUTAM',
      'nomPensionRel': 'WIFE',
      'permAddress': 'Flat No. 102, Plot No. 37/38, Vandana Mension, Surana Layout, Anant Nagar Nagpur 440013',
      'tempAddress': 'Flat No. 102, Plot No. 37/38, Vandana Mension, Surana Layout, Anant Nagar Nagpur 440013',
      'emergAddress': 'Moil Bhawan Katol Road Nagpur 440013',
      'spouse': 'Bhumeshwari Gautam',
      'spouseDob': '10-02-1979',
      'child1': 'Zinit Gautam',
      'childDob1': '05-08-2002',
      'child2': 'N/A',
      'childDob2': '',
      'child3': 'N/A',
      'childDob3': '',
      'mother': 'Laxmibai Gautam',
      'motherDob': '01-11-1944',
      'father': 'Narayan Gautam',
      'fatherDob': '14-07-1942',
      'other': 'N/A',
      'otherDob': '',
      'sepDate': 'N/A',
      'sepReason': 'N/A',
      'hireReason': 'New Position',
      'spouseAcc': 'N/A',
      'empRoll': 'RO',
      'nominees': [],
      'serviceHistory': [],
      'reportingOfficer': '446',
      'reportingOfficer1': '16194',
    },
    {
      'empNo': '4733',
      'name': 'Radheshyam Chandra',
      'status': 'Active',
      'group': 'Non - Executive',
      'subgroup': 'N7',
      'subgroupText': 'Non Executive-07',
      'position': 'Sr. Assistant (System)',
      'seniority': '2',
      'payscale': '26200-3%-47500',
      'dept': 'System',
      'subarea': 'Head Office Nag',
      'gender': 'Male',
      'deptName': 'System',
      'dob': '01-04-1976',
      'qual': 'M.A.,LLB,DIP.IN COMP.SCI.,',
      'basic': '45,190.00',
      'apptDate': '14-07-2008',
      'dosl': '01-01-2024',
      'dopp': '06-10-2025',
      'datePsc': 'N/A',
      'actDoj': '02-01-2024',
      'latPromo': 'N/A',
      'confDue': 'N/A',
      'internalRec': 'N/A',
      'regularization': 'N/A',
      'retireDate': '31-03-2036',
      'caste': 'OB',
      'marital': 'Married',
      'mobile': '7636274532',
      'email': 'CHANDRA4733@GMAIL.COM',
      'voter': 'N/A',
      'uan': '100289807052',
      'pension': '11458',
      'passport': '3263',
      'pan': 'ANKPC1401A',
      'gratuity': 'Rs. 7,05,563.79',
      'fb': 'N/A',
      'dl': 'R/20869/2002',
      'aadhar': '733033143391',
      'blood': 'O +VE',
      'praan': '110131149917',
      'ppo': 'N/A',
      'newMed': 'N/A',
      'oldMed': 'N/A',
      'penalty': 'N/A',
      'epf': 'MOMP',
      'pfNo': 'MP/JBP/134/7020',
      'pensionPf': 'MP/JBP/134/7020',
      'purchasePrice': 'Rs. 7,05,563.79',
      'fileNo': 'N/A',
      'bankKey': 'SBIN0004935',
      'bankAcc': '10280183226',
      'nomGratuity': 'HEMLATA RADHESHYAM',
      'nomGratuityRel': 'WIFE',
      'nomPf': 'HEMLATA RADHESHYAM',
      'nomPfRel': 'WIFE',
      'nomPension': 'HEMLATA RADHESHYAM',
      'nomPensionRel': 'WIFE',
      'permAddress': 'Vill- Kachanda, Tah-Jaijaipur Dist - Janjgir-Chapa Janjgir-Chap 495690',
      'tempAddress': 'At Post Ukwa, Tah.-Paraswada Distt.-Balaghat Ukwa 481105',
      'emergAddress': 'At Post Ukwa Tah.-Paraswada Ukwa 481105',
      'spouse': 'Hemlata Chandra Chandra',
      'spouseDob': '09-07-1987',
      'child1': 'Gunjan Chandra',
      'childDob1': '28-01-2010',
      'child2': 'Nayan Chandra',
      'childDob2': '01-07-2012',
      'child3': 'N/A',
      'childDob3': '',
      'mother': 'Satyabhama Chandra',
      'motherDob': '10-02-1940',
      'father': 'N/A',
      'fatherDob': '',
      'other': 'N/A',
      'otherDob': '',
      'sepDate': 'N/A',
      'sepReason': 'N/A',
      'hireReason': 'New Position',
      'spouseAcc': 'N/A',
      'empRoll': 'RO',
      'nominees': [],
      'serviceHistory': [],
      'reportingOfficer': '446',
      'reportingOfficer1': '16194',
    },
    {
      'empNo': '17110',
      'name': 'Sameer Banerjee',
      'status': 'Active',
      'group': 'Executive',
      'subgroup': 'MD',
      'subgroupText': 'Chairman/MD',
      'position': 'Chairman-cum-Managing Director',
      'seniority': '00000001',
      'payscale': '200000-370000',
      'dept': 'CMD',
      'subarea': 'Head Office Nag',
      'gender': 'Male',
      'deptName': 'Head Office CMD Secretariat',
      'dob': '28-08-1970',
      'qual': 'B.E.(Metallurgy)-91, MBA(Mktg.)-13, Certified Course Adv. St.Mgt-22',
      'basic': '2,37,990.00',
      'apptDate': '07-01-2026',
      'dosl': '07-01-2026',
      'dopp': '07-01-2026',
      'datePsc': 'N/A',
      'actDoj': '31-08-2030',
      'latPromo': 'N/A',
      'confDue': 'N/A',
      'internalRec': 'N/A',
      'regularization': 'N/A',
      'retireDate': '31-08-2030',
      'caste': 'NA',
      'marital': 'Married',
      'mobile': '9403578523',
      'email': 'CMD@MOIL.NIC.IN',
      'voter': 'N/A',
      'uan': '100882475525',
      'pension': 'N/A',
      'passport': 'N/A',
      'pan': 'ANAPS9304G',
      'gratuity': 'N/A',
      'fb': 'N/A',
      'dl': 'N/A',
      'aadhar': '966084981199',
      'blood': 'N/A',
      'praan': '110166000917',
      'ppo': 'N/A',
      'newMed': 'N/A',
      'oldMed': 'N/A',
      'penalty': 'N/A',
      'epf': 'SSPF',
      'pfNo': 'S1452',
      'pensionPf': 'NG/NAG/3664E/25076',
      'purchasePrice': 'N/A',
      'fileNo': 'N/A',
      'bankKey': 'SBIN0020728',
      'bankAcc': '33570488344',
      'nomGratuity': 'N/A',
      'nomGratuityRel': 'N/A',
      'nomPf': 'N/A',
      'nomPfRel': 'N/A',
      'nomPension': 'N/A',
      'nomPensionRel': 'N/A',
      'permAddress': 'Sector-75, Faridabad-121004  Faridabad 121004',
      'tempAddress': 'N/A',
      'emergAddress': 'N/A',
      'spouse': 'Lakshmi Sameer Banerjee',
      'spouseDob': '14-08-1973',
      'child1': 'N/A',
      'childDob1': '',
      'child2': 'N/A',
      'childDob2': '',
      'child3': 'N/A',
      'childDob3': '',
      'mother': 'N/A',
      'motherDob': '',
      'father': 'N/A',
      'fatherDob': '',
      'other': 'N/A',
      'otherDob': '',
      'sepDate': 'N/A',
      'sepReason': 'N/A',
      'hireReason': 'New Position',
      'spouseAcc': 'N/A',
      'empRoll': 'RO',
      'nominees': [],
      'serviceHistory': [],
      'reportingOfficer': '0',
      'reportingOfficer1': '0',
    }
  ];

  EmployeeModel _mapToModel(Map<String, dynamic> m) {
    return EmployeeModel(
      id: m['empNo'],
      name: m['name'],
      fatherSpouseName: m['father'] != 'N/A' ? m['father'] : m['spouse'],
      designation: m['position'],
      department: m['dept'],
      presentGrade: m['subgroupText'],
      dateOfBirth: m['dob'],
      joinDate: m['apptDate'],
      lastPromotionDate: m['latPromo'],
      appointmentType: m['group'],
      category: m['caste'],
      bloodGroup: m['blood'],
      gender: m['gender'],
      maritalStatus: m['marital'],
      employeeId: m['empNo'],
      basicSalary: m['basic'],
      presentPlaceOfPosting: m['subarea'],
      presentPostingDate: m['actDoj'],
      retirementDate: m['retireDate'],
      mobileNumber: m['mobile'],
      email: m['email'],
      uanNo: m['uan'],
      panNo: m['pan'],
      aadhaarNo: m['aadhar'],
      pranNo: m['praan'],
      pfNo: m['pfNo'],
      pensionNo: m['pension'],
      reportingOfficer: m['reportingOfficer'] ?? m['empRoll'] ?? '',
      reportingOfficer1: m['reportingOfficer1'] ?? '0',
      address: m['permAddress'],
      emergencyContact: m['mobile'],
      nominees: List<Map<String, dynamic>>.from(m['nominees'] ?? []),
      serviceHistory: List<Map<String, dynamic>>.from(m['serviceHistory'] ?? []),
    );
  }

  Future<void> fetchEmployeeProfile(String employeeId) async {
    _isLoading = true;
    notifyListeners();

    await Future.delayed(const Duration(milliseconds: 200));

    final match = rawEmployees.firstWhere((e) => e['empNo'] == employeeId, orElse: () => rawEmployees.first);
    _employee = _mapToModel(match);
    _isLoading = false;
    notifyListeners();
  }

  List<EmployeeModel> _employees = [];
  List<EmployeeModel> get employees => _employees;

  Future<void> fetchAllEmployees() async {
    _isLoading = true;
    notifyListeners();

    await Future.delayed(const Duration(milliseconds: 200));

    _employees = rawEmployees.map((e) => _mapToModel(e)).toList();
    _isLoading = false;
    notifyListeners();
  }

  Future<bool> updateProfile({
    String? mobileNumber,
    String? address,
    String? emergencyContact,
  }) async {
    try {
      await Future.delayed(const Duration(seconds: 1));
      if (_employee != null) {
        _employee = EmployeeModel(
          id: _employee!.id,
          name: _employee!.name,
          fatherSpouseName: _employee!.fatherSpouseName,
          designation: _employee!.designation,
          department: _employee!.department,
          presentGrade: _employee!.presentGrade,
          dateOfBirth: _employee!.dateOfBirth,
          joinDate: _employee!.joinDate,
          lastPromotionDate: _employee!.lastPromotionDate,
          appointmentType: _employee!.appointmentType,
          category: _employee!.category,
          bloodGroup: _employee!.bloodGroup,
          gender: _employee!.gender,
          maritalStatus: _employee!.maritalStatus,
          employeeId: _employee!.employeeId,
          basicSalary: _employee!.basicSalary,
          presentPlaceOfPosting: _employee!.presentPlaceOfPosting,
          presentPostingDate: _employee!.presentPostingDate,
          retirementDate: _employee!.retirementDate,
          mobileNumber: mobileNumber ?? _employee!.mobileNumber,
          email: _employee!.email,
          uanNo: _employee!.uanNo,
          panNo: _employee!.panNo,
          aadhaarNo: _employee!.aadhaarNo,
          pranNo: _employee!.pranNo,
          pfNo: _employee!.pfNo,
          pensionNo: _employee!.pensionNo,
          reportingOfficer: _employee!.reportingOfficer,
          reportingOfficer1: _employee!.reportingOfficer1,
          address: address ?? _employee!.address,
          emergencyContact: emergencyContact ?? _employee!.emergencyContact,
          nominees: _employee!.nominees,
          serviceHistory: _employee!.serviceHistory,
        );
      }
      notifyListeners();
      return true;
    } catch (e) {
      return false;
    }
  }
}
