// lib/modules/profile/controller/profile_controller.dart

import 'package:flutter/material.dart';
import '../../../model/employee_model.dart';

class ProfileController extends ChangeNotifier {
  bool _isLoading = false;
  EmployeeModel? _employee;

  bool get isLoading => _isLoading;
  EmployeeModel? get employee => _employee;

  static final List<Map<String, dynamic>> rawEmployees = [
    {
      'empNo': '283',
      'name': 'Nitin Purushottam Kajarekar',
      'status': 'Active',
      'group': 'Executive',
      'subgroup': 'E8',
      'subgroupText': 'GM',
      'position': 'General Manager-Finance',
      'seniority': '00000001',
      'payscale': '120000-280000',
      'dept': 'Finance',
      'subarea': 'Balaghat Mine',
      'gender': 'Male',
      'deptName': 'Finance',
      'dob': '27/08/1967',
      'qual': 'B.COM.,C.A.',
      'basic': '1,62,460.00',
      'apptDate': '15/04/1998',
      'dosl': '01/07/2024',
      'dopp': '19/05/2011',
      'datePsc': 'N/A',
      'actDoj': '06/08/2024',
      'latPromo': 'N/A',
      'confDue': 'N/A',
      'internalRec': 'N/A',
      'regularization': 'N/A',
      'retireDate': '31/08/2027',
      'caste': 'OT',
      'marital': 'Married',
      'mobile': '123456789',
      'email': 'ABC@gmail.com',
      'voter': '1234567890',
      'uan': '325',
      'pension': '100225',
      'passport': '2000225',
      'pan': '1000225',
      'gratuity': '2499999975',
      'fb': '02135',
      'dl': 'DL000225',
      'aadhar': 'AN0000225',
      'blood': 'O+',
      'praan': '110189850382',
      'ppo': 'N/A',
      'newMed': 'N/A',
      'oldMed': 'N/A',
      'penalty': 'N/A',
      'epf': 'SSPF',
      'pfNo': 'K639',
      'pensionPf': 'NG/NAG/3664E/1113',
      'purchasePrice': 'Rs. 42,27,560.10',
      'fileNo': '392',
      'bankKey': 'BK00225',
      'bankAcc': '100000225',
      'nomGratuity': 'MRS. MRUNAL KAJAREKAR',
      'nomGratuityRel': 'WIFE',
      'nomPf': 'MRS. MRUNAL KAJAREKAR',
      'nomPfRel': 'WIFE',
      'nomPension': 'MRS. MRUNAL KAJAREKAR',
      'nomPensionRel': 'WIFE',
      'permAddress': 'Bhavan',
      'tempAddress': 'TA Bhavan',
      'emergAddress': 'EA Bhavan',
      'spouse': 'Mrunal Kajarekar',
      'spouseDob': '20/03/1997',
      'child1': 'Ajinkya Kajarekar',
      'childDob1': '20/03/1997',
      'child2': 'Aamod Kajarekar',
      'childDob2': '25/01/2009',
      'child3': 'N/A',
      'childDob3': '',
      'mother': 'Nalini Kajarekar',
      'motherDob': '10-02-1942',
      'father': 'Late Purushottam Kajarekar',
      'fatherDob': '25-06-1932',
      'other': 'N/A',
      'otherDob': '',
      'sepDate': 'N/A',
      'sepReason': 'N/A',
      'hireReason': 'New Position',
      'spouseAcc': 'N/A',
      'empRoll': 'RO',
      'nominees': [],
      'serviceHistory': [],
    },
    {
      'empNo': '422',
      'name': 'Kartik R. Shah',
      'status': 'Active',
      'group': 'Executive',
      'subgroup': 'E5',
      'subgroupText': 'Asst. Gen. Manager',
      'position': 'Assistant General Manager-Finance',
      'seniority': '00000012',
      'payscale': '80000-220000',
      'dept': 'Finance',
      'subarea': 'Chikla Mine',
      'gender': 'Male',
      'deptName': 'Purchase Payment Cell',
      'dob': '18/04/1980',
      'qual': 'B.COM.,C.A.[INTER]',
      'basic': '87,100.00',
      'apptDate': '15/11/2006',
      'dosl': '01/07/2023',
      'dopp': '07/06/2014',
      'datePsc': 'N/A',
      'actDoj': '28/11/2023',
      'latPromo': 'N/A',
      'confDue': '30/07/2019',
      'internalRec': 'N/A',
      'regularization': 'N/A',
      'retireDate': '30/04/2040',
      'caste': 'OT',
      'marital': 'Married',
      'mobile': '123456789',
      'email': 'ABC@gmail.com',
      'voter': '1234567890',
      'uan': '417',
      'pension': '100317',
      'passport': '2000317',
      'pan': '1000317',
      'gratuity': '3522222187',
      'fb': '02142',
      'dl': 'DL000317',
      'aadhar': 'AN0000317',
      'blood': 'A+',
      'praan': '110031691209',
      'ppo': 'N/A',
      'newMed': 'N/A',
      'oldMed': 'N/A',
      'penalty': 'N/A',
      'epf': 'SSPF',
      'pfNo': 'S1362',
      'pensionPf': 'MP/JBP/133E/10062',
      'purchasePrice': 'Rs. 14,23,108.05',
      'fileNo': '533',
      'bankKey': 'BK00317',
      'bankAcc': '100000317',
      'nomGratuity': 'MRS. AMBIKA SHAH',
      'nomGratuityRel': 'WIFE',
      'nomPf': 'MRS. AMBIKA SHAH',
      'nomPfRel': 'WIFE',
      'nomPension': 'MRS. AMBIKA SHAH',
      'nomPensionRel': 'WIFE',
      'permAddress': 'Bhavan',
      'tempAddress': 'TA Bhavan',
      'emergAddress': 'EA Bhavan',
      'spouse': 'Ambika Shah',
      'spouseDob': '09/11/1981',
      'child1': 'Radhika Shah',
      'childDob1': '05/02/2010',
      'child2': 'Saket Shah',
      'childDob2': '26/11/2011',
      'child3': 'N/A',
      'childDob3': '',
      'mother': 'Lalita Shah',
      'motherDob': '20/04/1957',
      'father': 'Ramakant Shah',
      'fatherDob': '15/09/1951',
      'other': 'N/A',
      'otherDob': '',
      'sepDate': 'N/A',
      'sepReason': 'N/A',
      'hireReason': 'New Position',
      'spouseAcc': 'N/A',
      'empRoll': 'Emp1',
      'nominees': [],
      'serviceHistory': [],
    },
    {
      'empNo': '431',
      'name': 'Arvind B Gajbhiye',
      'status': 'Active',
      'group': 'Executive',
      'subgroup': 'E7',
      'subgroupText': 'Jt. General Manager',
      'position': 'Joint General Manager-Finance',
      'seniority': '00000002',
      'payscale': '100000-260000',
      'dept': 'Finance',
      'subarea': 'Dongri Buzurg Mine',
      'gender': 'Male',
      'deptName': 'Corporate Finance',
      'dob': '25/06/1967',
      'qual': 'M.COM.,C.A.',
      'basic': '1,17,490.00',
      'apptDate': '24/06/2007',
      'dosl': '01/01/2021',
      'dopp': '19/06/2012',
      'datePsc': 'N/A',
      'actDoj': '31/05/2021',
      'latPromo': 'N/A',
      'confDue': 'N/A',
      'internalRec': 'N/A',
      'regularization': 'N/A',
      'retireDate': '30/06/2027',
      'caste': 'SC',
      'marital': 'Married',
      'mobile': '123456789',
      'email': 'ABC@gmail.com',
      'voter': '1234567890',
      'uan': '426',
      'pension': '100326',
      'passport': '2000326',
      'pan': '1000326',
      'gratuity': '3622222186',
      'fb': '02138',
      'dl': 'DL000326',
      'aadhar': 'AN0000326',
      'blood': 'O+',
      'praan': '110198016576',
      'ppo': 'N/A',
      'newMed': 'N/A',
      'oldMed': 'N/A',
      'penalty': 'N/A',
      'epf': 'MOMH',
      'pfNo': 'NG/NAG/3600/4443',
      'pensionPf': 'NG/NAG/3600/4443',
      'purchasePrice': 'Rs. 19,31,810.15',
      'fileNo': '542',
      'bankKey': 'BK00326',
      'bankAcc': '100000326',
      'nomGratuity': 'MRS. RUPALI GAJBHIYE',
      'nomGratuityRel': 'WIFE',
      'nomPf': 'MRS. RUPALI GAJBHIYE',
      'nomPfRel': 'WIFE',
      'nomPension': 'MRS. RUPALI GAJBHIYE',
      'nomPensionRel': 'WIFE',
      'permAddress': 'Bhavan',
      'tempAddress': 'TA Bhavan',
      'emergAddress': 'EA Bhavan',
      'spouse': 'Rupali Gajbhiye',
      'spouseDob': '06/09/1978',
      'child1': 'Shlok Gajbhiye',
      'childDob1': '27/07/1999',
      'child2': 'Aarya Gajbhiye',
      'childDob2': '16/10/2004',
      'child3': 'N/A',
      'childDob3': '',
      'mother': 'Karuna Gajbhiye',
      'motherDob': '18/10/1942',
      'father': 'N/A',
      'fatherDob': '',
      'other': 'N/A',
      'otherDob': '',
      'sepDate': 'N/A',
      'sepReason': 'N/A',
      'hireReason': 'New Position',
      'spouseAcc': 'N/A',
      'empRoll': 'Emp2',
      'nominees': [],
      'serviceHistory': [],
    },
    {
      'empNo': '446',
      'name': 'Raja Talathoti',
      'status': 'Active',
      'group': 'Executive',
      'subgroup': 'E6',
      'subgroupText': 'DGM',
      'position': 'Deputy General Manager-System',
      'seniority': '00000001',
      'payscale': '90000-240000',
      'dept': 'System',
      'subarea': 'Head Office Nag',
      'gender': 'Male',
      'deptName': 'System',
      'dob': '26/04/1976',
      'qual': 'D.C.M.E., \'A\' LEVEL, \'B\' LEVEL(MCA)',
      'basic': '1,01,760.00',
      'apptDate': '11/12/2007',
      'dosl': '01/07/2024',
      'dopp': '08/05/2017',
      'datePsc': 'N/A',
      'actDoj': '08/08/2024',
      'latPromo': '01/07/2024',
      'confDue': 'N/A',
      'internalRec': 'N/A',
      'regularization': 'N/A',
      'retireDate': '30/04/2036',
      'caste': 'Scheduled Castes',
      'marital': 'Married',
      'mobile': '9860801149',
      'email': 'RAJA@MOIL.NIC.IN',
      'voter': '1234567890',
      'uan': '100292843101',
      'pension': '100341',
      'passport': '2000341',
      'pan': 'ADIPT5111G',
      'gratuity': '3788888851',
      'fb': '00000446',
      'dl': 'DL000341',
      'aadhar': '557092546386',
      'blood': 'A+',
      'praan': '110153877952',
      'ppo': 'N/A',
      'newMed': 'N/A',
      'oldMed': 'N/A',
      'penalty': 'N/A',
      'epf': 'SSPF',
      'pfNo': 'T1382',
      'pensionPf': 'MP/JBP/133E/10027',
      'purchasePrice': 'Rs. 15,72,808.07',
      'fileNo': '559',
      'bankKey': 'BK00341',
      'bankAcc': '100000341',
      'nomGratuity': 'MRS. ANITHA TALATHOTI',
      'nomGratuityRel': 'WIFE',
      'nomPf': 'MRS. ANITHA TALATHOTI',
      'nomPfRel': 'WIFE',
      'nomPension': 'MRS. ANITHA TALATHOTI',
      'nomPensionRel': 'WIFE',
      'permAddress': 'Srinivasa Rao Epuru (vill-po) Ananthavaram (via), Tenali(Tq) Guntur 522301 IN',
      'tempAddress': 'House No 54 (g+1) Orange city park kamptee road kamptee 441002 IN',
      'emergAddress': 'Srinivasa Rao Epuru(Vil-Po), Guntur(Dt) 522301 IN',
      'spouse': 'Anitha Talathoti',
      'spouseDob': '06/08/1988',
      'child1': 'Pavitra Talathoti',
      'childDob1': '12/01/2009',
      'child2': 'Vikranth Talathoti',
      'childDob2': '26/12/2013',
      'child3': 'N/A',
      'childDob3': '',
      'mother': 'Chiranjeevi Talathoti',
      'motherDob': '16/01/1960',
      'father': 'Srinivasa Rao Talathoti',
      'fatherDob': '04/05/1953',
      'other': 'N/A',
      'otherDob': '',
      'sepDate': 'N/A',
      'sepReason': 'N/A',
      'hireReason': 'New Position',
      'spouseAcc': 'N/A',
      'empRoll': 'Emp2',
      'nominees': [
        {'benefit': 'Benevolent Fund Benefit', 'name': 'Mrs. Anitha Talathoti', 'relation': 'Wife', 'dob': '06-08-1988', 'percentage': '100.00'},
        {'benefit': 'Gratuity Benefit', 'name': 'Mrs. Anitha Talathoti', 'relation': 'Wife', 'dob': '06-08-1988', 'percentage': '100.00'},
        {'benefit': 'PF Benefit', 'name': 'Mrs. Anitha Talathoti', 'relation': 'Wife', 'dob': '06-08-1988', 'percentage': '100.00'},
        {'benefit': 'Pension Benefit', 'name': 'Mrs. Anitha Talathoti', 'relation': 'Wife', 'dob': '06-08-1988', 'percentage': '100.00'},
      ],
      'serviceHistory': [
        {'designation': 'Deputy General Manager-System', 'grade': 'E6', 'location': 'Head Office', 'from': '08-08-2024', 'to': 'Till Date', 'payscale': '90000-240000'},
        {'designation': 'Asst.General Manager-System', 'grade': 'E5', 'location': 'Head Office', 'from': '01-01-2020', 'to': '07-08-2024', 'payscale': '80000-220000'},
        {'designation': 'Chief Manager-System', 'grade': 'E4', 'location': 'Head Office', 'from': '01-01-2018', 'to': '31-12-2019', 'payscale': '70000-200000'},
        {'designation': 'Chief Manager-System', 'grade': 'E3', 'location': 'Head Office', 'from': '01-06-2017', 'to': '31-12-2017', 'payscale': '24900-50500'},
        {'designation': 'Chief Manager-System', 'grade': 'E3', 'location': 'Kandri', 'from': '06-05-2016', 'to': '31-05-2017', 'payscale': '24900-50500'},
        {'designation': 'Senior Manager System', 'grade': 'E2', 'location': 'Kandri', 'from': '01-04-2016', 'to': '05-05-2016', 'payscale': 'N/A'},
        {'designation': 'Sr. Manager-System', 'grade': 'E3', 'location': 'Kandri', 'from': '21-09-2011', 'to': '31-03-2016', 'payscale': '20600-46500'},
        {'designation': 'Manager-System', 'grade': 'E2', 'location': 'Kandri', 'from': '04-02-2008', 'to': '20-09-2011', 'payscale': '8600-2500-14600'},
        {'designation': 'Manager-System', 'grade': 'E2', 'location': 'Balaghat', 'from': '11-12-2007', 'to': '03-02-2008', 'payscale': '8600-2500-14600'},
      ],
    },
    {
      'empNo': '491',
      'name': 'Sushant Sudhakar Khursange',
      'status': 'Active',
      'group': 'Executive',
      'subgroup': 'E5',
      'subgroupText': 'Asst. Gen. Manager',
      'position': 'Assistant General Manager-System',
      'seniority': '00000005',
      'payscale': '80000-220000',
      'dept': 'System',
      'subarea': 'Kandri Mine',
      'gender': 'Male',
      'deptName': 'System',
      'dob': '05-12-1980',
      'qual': 'B.Sc., M.C.A.',
      'basic': '81,170.00',
      'apptDate': '03/03/2009',
      'dosl': '01/07/2025',
      'dopp': '16/08/2025',
      'datePsc': 'N/A',
      'actDoj': '16/08/2025',
      'latPromo': 'N/A',
      'confDue': 'N/A',
      'internalRec': 'N/A',
      'regularization': 'N/A',
      'retireDate': '31/12/2040',
      'caste': 'OB',
      'marital': 'Married',
      'mobile': '123456789',
      'email': 'ABC@gmail.com',
      'voter': '1234567890',
      'uan': '486',
      'pension': '100386',
      'passport': '2000386',
      'pan': '1000386',
      'gratuity': '4288888846',
      'fb': '08878',
      'dl': 'DL000386',
      'aadhar': 'AN0000386',
      'blood': 'B+',
      'praan': '110187299933',
      'ppo': 'N/A',
      'newMed': 'N/A',
      'oldMed': 'N/A',
      'penalty': 'N/A',
      'epf': 'MOMP',
      'pfNo': 'MP/JBP/128/13324',
      'pensionPf': 'MP/JBP/128/13324',
      'purchasePrice': 'Rs. 11,61,255.11',
      'fileNo': '631',
      'bankKey': 'BK00386',
      'bankAcc': '100000386',
      'nomGratuity': 'SUREKHA KHURSANGE',
      'nomGratuityRel': 'WIFE',
      'nomPf': 'SUREKHA KHURSANGE',
      'nomPfRel': 'WIFE',
      'nomPension': 'SUREKHA KHURSANGE',
      'nomPensionRel': 'WIFE',
      'permAddress': 'Bhavan',
      'tempAddress': 'TA Bhavan',
      'emergAddress': 'EA Bhavan',
      'spouse': 'Surekha Khursange',
      'spouseDob': '09/08/1986',
      'child1': 'Swarit Khursange',
      'childDob1': '31/10/2013',
      'child2': 'N/A',
      'childDob2': '',
      'child3': 'N/A',
      'childDob3': '',
      'mother': 'Vimal Khursange',
      'motherDob': '05/09/1952',
      'father': 'Late Sudhakar Khursange',
      'fatherDob': '05/04/1951',
      'other': 'N/A',
      'otherDob': '',
      'sepDate': 'N/A',
      'sepReason': 'N/A',
      'hireReason': 'New Position',
      'spouseAcc': 'N/A',
      'empRoll': 'Emp1',
      'nominees': [],
      'serviceHistory': [],
    },
    {
      'empNo': '540',
      'name': 'Swapnil Kanthiram Manpe',
      'status': 'Active',
      'group': 'Executive',
      'subgroup': 'E4',
      'subgroupText': 'Chief Manager',
      'position': 'Chief Manager (System)',
      'seniority': '00000007',
      'payscale': '70000-200000',
      'dept': 'System',
      'subarea': 'Mansar Mine',
      'gender': 'Male',
      'deptName': 'System',
      'dob': '12/09/1986',
      'qual': 'B.E.[IT]',
      'basic': '70,000.00',
      'apptDate': '02/12/2011',
      'dosl': '01/07/2025',
      'dopp': '16/08/2025',
      'datePsc': 'N/A',
      'actDoj': '16/08/2025',
      'latPromo': '31/12/2017',
      'confDue': 'N/A',
      'internalRec': 'N/A',
      'regularization': 'N/A',
      'retireDate': '30/09/2046',
      'caste': 'SC',
      'marital': 'Married',
      'mobile': '123456789',
      'email': 'ABC@gmail.com',
      'voter': '1234567890',
      'uan': '535',
      'pension': '100435',
      'passport': '2000435',
      'pan': '100435',
      'gratuity': '4833333285',
      'fb': '02606',
      'dl': 'DL000435',
      'aadhar': 'AN0000435',
      'blood': 'O+',
      'praan': '110119993569',
      'ppo': 'N/A',
      'newMed': 'N/A',
      'oldMed': 'N/A',
      'penalty': 'N/A',
      'epf': 'MOMP',
      'pfNo': 'MP/JBP/133/13821',
      'pensionPf': 'MP/JBP/133/13821',
      'purchasePrice': 'Rs. 8,70,181.18',
      'fileNo': '693',
      'bankKey': 'BK00435',
      'bankAcc': '100000435',
      'nomGratuity': 'MRS SHWETA MANPE',
      'nomGratuityRel': 'WIFE',
      'nomPf': 'MRS SHWETA MANPE',
      'nomPfRel': 'WIFE',
      'nomPension': 'MRS SHWETA MANPE',
      'nomPensionRel': 'WIFE',
      'permAddress': 'Bhavan',
      'tempAddress': 'TA Bhavan',
      'emergAddress': 'EA Bhavan',
      'spouse': 'MRS SHWETA MANPE',
      'spouseDob': '22/11/1990',
      'child1': 'Prashil Manpe',
      'childDob1': '10/07/2021',
      'child2': 'N/A',
      'childDob2': '',
      'child3': 'N/A',
      'childDob3': '',
      'mother': 'Karuna Manpe',
      'motherDob': '01/01/1959',
      'father': 'Kanthiram Manpe',
      'fatherDob': '01/07/1957',
      'other': 'N/A',
      'otherDob': '',
      'sepDate': 'N/A',
      'sepReason': 'N/A',
      'hireReason': 'New Position',
      'spouseAcc': 'N/A',
      'empRoll': 'Emp2',
      'nominees': [],
      'serviceHistory': [],
    },
    {
      'empNo': '16194',
      'name': 'Rakesh Tumane',
      'status': 'Active',
      'group': 'Executive',
      'subgroup': 'DR',
      'subgroupText': 'Directors',
      'position': 'Director-Finance',
      'seniority': '00000001',
      'payscale': '180000-340000',
      'dept': 'Director (Fin.)',
      'subarea': 'Ukwa Mine',
      'gender': 'Male',
      'deptName': 'Head Office Finance',
      'dob': '20/08/1970',
      'qual': 'MBA, FCMA,CIMA,AICPA, MBA (Fin), BE (Comp. Science), Diploma in French',
      'basic': '2,54,480.00',
      'apptDate': '28/09/2017',
      'dosl': '28/09/2017',
      'dopp': '28/09/2017',
      'datePsc': 'N/A',
      'actDoj': 'N/A',
      'latPromo': '27/09/2018',
      'confDue': 'N/A',
      'internalRec': 'N/A',
      'regularization': 'N/A',
      'retireDate': '31/08/2030',
      'caste': 'OT',
      'marital': 'Married',
      'mobile': '123456789',
      'email': 'ABC@gmail.com',
      'voter': '1234567890',
      'uan': '9622',
      'pension': '109522',
      'passport': '2009522',
      'pan': '1009522',
      'gratuity': '105799998942',
      'fb': 'N/A',
      'dl': 'DL009522',
      'aadhar': 'AN009522',
      'blood': 'O+',
      'praan': '110018121610',
      'ppo': 'N/A',
      'newMed': 'N/A',
      'oldMed': 'N/A',
      'penalty': 'N/A',
      'epf': 'SSPF',
      'pfNo': 'T1445',
      'pensionPf': 'NG/NAG/3664E/25070',
      'purchasePrice': 'Rs. 3532552.35',
      'fileNo': '824',
      'bankKey': 'BK09522',
      'bankAcc': '100009522',
      'nomGratuity': 'MRS. LEENA TUMANE',
      'nomGratuityRel': 'WIFE',
      'nomPf': 'MRS. LEENA TUMANE',
      'nomPfRel': 'WIFE',
      'nomPension': 'MRS. LEENA TUMANE',
      'nomPensionRel': 'WIFE',
      'permAddress': 'Bhavan',
      'tempAddress': 'TA Bhavan',
      'emergAddress': 'EA Bhavan',
      'spouse': 'Leena Tumane',
      'spouseDob': '18/06/1977',
      'child1': 'Rekha Shreshtha Tumane',
      'childDob1': '16/10/2001',
      'child2': 'N/A',
      'childDob2': '',
      'child3': 'Shiv Tumane',
      'childDob3': '28/01/2010',
      'mother': 'Rekha Tumane',
      'motherDob': '07/07/1950',
      'father': 'Madhusudan Tumane',
      'fatherDob': '13/11/1945',
      'other': 'N/A',
      'otherDob': '',
      'sepDate': 'N/A',
      'sepReason': 'N/A',
      'hireReason': 'New Position',
      'spouseAcc': 'N/A',
      'empRoll': 'RO1',
      'nominees': [],
      'serviceHistory': [],
    }
  ];

  EmployeeModel _mapToModel(Map<String, dynamic> m) {
    return EmployeeModel(
      id: m['empNo'],
      name: m['name'],
      fatherSpouseName: m['father'] != 'N/A' ? m['father'] : m['spouse'],
      designation: m['position'],
      department: m['dept'],
      presentGrade: m['subgroupText'],
      dateOfBirth: m['dob'],
      joinDate: m['apptDate'],
      lastPromotionDate: m['latPromo'],
      appointmentType: m['group'],
      category: m['caste'],
      bloodGroup: m['blood'],
      gender: m['gender'],
      maritalStatus: m['marital'],
      employeeId: m['empNo'],
      basicSalary: m['basic'],
      presentPlaceOfPosting: m['subarea'],
      presentPostingDate: m['actDoj'],
      retirementDate: m['retireDate'],
      mobileNumber: m['mobile'],
      email: m['email'],
      uanNo: m['uan'],
      panNo: m['pan'],
      aadhaarNo: m['aadhar'],
      pranNo: m['praan'],
      pfNo: m['pfNo'],
      pensionNo: m['pension'],
      reportingOfficer: m['empRoll'],
      address: m['permAddress'],
      emergencyContact: m['mobile'],
      nominees: List<Map<String, dynamic>>.from(m['nominees'] ?? []),
      serviceHistory: List<Map<String, dynamic>>.from(m['serviceHistory'] ?? []),
    );
  }

  Future<void> fetchEmployeeProfile(String employeeId) async {
    _isLoading = true;
    notifyListeners();

    await Future.delayed(const Duration(milliseconds: 200));

    final match = rawEmployees.firstWhere((e) => e['empNo'] == employeeId, orElse: () => rawEmployees.first);
    _employee = _mapToModel(match);
    _isLoading = false;
    notifyListeners();
  }

  List<EmployeeModel> _employees = [];
  List<EmployeeModel> get employees => _employees;

  Future<void> fetchAllEmployees() async {
    _isLoading = true;
    notifyListeners();

    await Future.delayed(const Duration(milliseconds: 200));

    _employees = rawEmployees.map((e) => _mapToModel(e)).toList();
    _isLoading = false;
    notifyListeners();
  }

  Future<bool> updateProfile({
    String? mobileNumber,
    String? address,
    String? emergencyContact,
  }) async {
    try {
      await Future.delayed(const Duration(seconds: 1));
      if (_employee != null) {
        _employee = EmployeeModel(
          id: _employee!.id,
          name: _employee!.name,
          fatherSpouseName: _employee!.fatherSpouseName,
          designation: _employee!.designation,
          department: _employee!.department,
          presentGrade: _employee!.presentGrade,
          dateOfBirth: _employee!.dateOfBirth,
          joinDate: _employee!.joinDate,
          lastPromotionDate: _employee!.lastPromotionDate,
          appointmentType: _employee!.appointmentType,
          category: _employee!.category,
          bloodGroup: _employee!.bloodGroup,
          gender: _employee!.gender,
          maritalStatus: _employee!.maritalStatus,
          employeeId: _employee!.employeeId,
          basicSalary: _employee!.basicSalary,
          presentPlaceOfPosting: _employee!.presentPlaceOfPosting,
          presentPostingDate: _employee!.presentPostingDate,
          retirementDate: _employee!.retirementDate,
          mobileNumber: mobileNumber ?? _employee!.mobileNumber,
          email: _employee!.email,
          uanNo: _employee!.uanNo,
          panNo: _employee!.panNo,
          aadhaarNo: _employee!.aadhaarNo,
          pranNo: _employee!.pranNo,
          pfNo: _employee!.pfNo,
          pensionNo: _employee!.pensionNo,
          reportingOfficer: _employee!.reportingOfficer,
          address: address ?? _employee!.address,
          emergencyContact: emergencyContact ?? _employee!.emergencyContact,
          nominees: _employee!.nominees,
          serviceHistory: _employee!.serviceHistory,
        );
      }
      notifyListeners();
      return true;
    } catch (e) {
      return false;
    }
  }
}
