name: Automated Web Release & Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Web Release
        run: flutter build web --base-href "/test/moil_hr_app/" --release

      - name: Sync Web Release Bundle
        run: |
          mkdir -p deploy_output
          cp -r build/web/* deploy_output/
